// <auto-generated />
using DockService.Core.Models;
using DockService.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DockService.Infrastructure.Migrations
{
    [DbContext(typeof(DockDbContext))]
    [Migration("20180524073558_AddMissingContainersToShip")]
    partial class AddMissingContainersToShip
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DockService.Core.Models.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SerialShippingContainerCode");

                    b.Property<Guid?>("ShipDBKey");

                    b.HasKey("Id");

                    b.HasIndex("ShipDBKey");

                    b.ToTable("Container");
                });

            modelBuilder.Entity("DockService.Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ContainerId");

                    b.Property<string>("Name");

                    b.Property<int>("ProductType");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("DockService.Core.Models.Ship", b =>
                {
                    b.Property<Guid>("DBKey")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CustomerId");

                    b.Property<Guid>("Id");

                    b.Property<string>("Name");

                    b.HasKey("DBKey");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("DockService.Core.Models.Container", b =>
                {
                    b.HasOne("DockService.Core.Models.Ship")
                        .WithMany("Containers")
                        .HasForeignKey("ShipDBKey");
                });

            modelBuilder.Entity("DockService.Core.Models.Product", b =>
                {
                    b.HasOne("DockService.Core.Models.Container")
                        .WithMany("Products")
                        .HasForeignKey("ContainerId");
                });
#pragma warning restore 612, 618
        }
    }
}
